# Hydro Bitcoin Mining Optimizer Configuration

# ASIC Specifications
asic:
  model: "Whatsminer M63s++ Hydro"
  hash_rate_th: 460
  watts_per_th: 15.5
  price_usd_per_th: 14.9

# Operating Costs
operating_costs:
  annual_usd: 50000  # Annual operating expenses
  
# Simulation Parameters
simulation:
  n_simulations: 200   # Number of Monte Carlo simulations (reduced for speed)
  fleet_step: 15       # Step size for fleet optimization (increased for fewer tests)
  projection_years: 2  # Years to project forward (reduced for speed)

# Economic Scenarios
scenarios:
  bear:
    name: "Bear Market"
    difficulty_growth_annual: 0.20  # 20% annual growth
    price_change_annual: -0.30      # -30% annual change
    description: "Crypto winter scenario with declining prices"
    
  base:
    name: "Base Case"
    difficulty_growth_annual: 0.35  # 35% annual growth
    price_change_annual: 0.15       # 15% annual growth
    description: "Moderate growth continuing current trends"
    
  bull:
    name: "Bull Market"
    difficulty_growth_annual: 0.50  # 50% annual growth
    price_change_annual: 0.50       # 50% annual growth
    description: "Strong adoption and institutional investment"
    
  custom:
    name: "Custom"
    difficulty_growth_annual: 0.00  # Placeholder, user will override
    price_change_annual: 0.00       # Placeholder, user will override
    description: "User-defined custom scenario"

# Financial Parameters
financial:
  pool_fee_percent: 0.02             # 2% mining pool fee